#configurando bd
spring.datasource.url=jdbc:postgresql://localhost:5432/crud-springboot
spring.datasource.username=postgres
spring.datasource.password=1234

spring.application.name=springboot

#configurando porta da aplicacao
server.port=2005

#faz update das entidades das entitys do model automaticamente (CREATE, ALTER TABLE)
spring.jpa.hibernate.ddl-auto=update

#Elimina logs desnecessarias quando subindo a aplicacao.
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#Acessar documentacao de endpoints gerada pelo swagger default = /swagger-ui/index.html
springdoc.swagger-ui.path=/documentacao

#Lidando com incompatibilidade do Swagger com o hateos
#springdoc.show-hateoas=false
#spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocHateoasConfiguration


